export const GET_ALL_STICK_CONTROL_EXERCISES_REQUEST =
  "GET_ALL_STICK_CONTROL_EXERCISES_REQUEST";
export const GET_ALL_STICK_CONTROL_EXERCISES_SUCCESS =
  "GET_ALL_STICK_CONTROL_EXERCISES_SUCCESS";
export const GET_ALL_STICK_CONTROL_EXERCISES_FAIL =
  "GET_ALL_STICK_CONTROL_EXERCISES_FAIL";
export const GET_RANDOM_STICK_CONTROL_EXERCISE_REQUEST =
  "GET_RANDOM_STICK_CONTROL_EXERCISE_REQUEST";
export const GET_RANDOM_STICK_CONTROL_EXERCISE_SUCCESS =
  "GET_RANDOM_STICK_CONTROL_EXERCISE_SUCCESS";
export const GET_RANDOM_STICK_CONTROL_EXERCISE_FAIL =
  "GET_RANDOM_STICK_CONTROL_EXERCISE_FAIL";
export const GET_CURRENT_STICK_CONTROL_EXERCISE_REQUEST =
  "GET_CURRENT_STICK_CONTROL_EXERCISE_REQUEST";
export const GET_CURRENT_STICK_CONTROL_EXERCISE_SUCCESS =
  "GET_CURRENT_STICK_CONTROL_EXERCISE_SUCCESS";
export const GET_CURRENT_STICK_CONTROL_EXERCISE_FAIL =
  "GET_CURRENT_STICK_CONTROL_EXERCISE_FAIL";
