export const GET_ALL_EXERCISES_REQUEST = "GET_ALL_EXERCISES_REQUEST";
export const GET_ALL_EXERCISES_SUCCESS = "GET_ALL_EXERCISES_SUCCESS";
export const GET_ALL_EXERCISES_FAIL = "GET_ALL_EXERCISES_FAIL";
