const singleBeatCombinations = [
  {
    section: "Single Beat Combinations",
    exercise: 1,
    sticking: "RLRLRLRLRLRLRLRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 1,
      sticking: "RLRLRLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 1,
      sticking: "RLRLRLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 2,
    sticking: "LRLRLRLRLRLRLRLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 2,
      sticking: "LRLRLRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 2,
      sticking: "LRLRLRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 3,
    sticking: "RRLLRRLLRRLLRRLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 3,
      sticking: "RRLLRRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 3,
      sticking: "RRLLRRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 4,
    sticking: "LLRRLLRRLLRRLLRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 4,
      sticking: "LLRRLLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 4,
      sticking: "LLRRLLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 5,
    sticking: "RLRRLRLLRLRRLRLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 5,
      sticking: "RLRRLRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 5,
      sticking: "RLRRLRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 6,
    sticking: "RLLRLRRLRLLRLRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 6,
      sticking: "RLLRLRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 6,
      sticking: "RLLRLRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 7,
    sticking: "RRLRLLRLRRLRLLRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 7,
      sticking: "RRLRLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 7,
      sticking: "RRLRLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 8,
    sticking: "RLRLLRLRRLRLLRLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 8,
      sticking: "RLRLLRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 8,
      sticking: "RLRLLRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 9,
    sticking: "RRRLRRRLRRRLRRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 9,
      sticking: "RRRLRRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 9,
      sticking: "RRRLRRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 10,
    sticking: "LLLRLLLRLLLRLLLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 10,
      sticking: "LLLRLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 10,
      sticking: "LLLRLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 11,
    sticking: "RLLLRLLLRLLLRLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 11,
      sticking: "RLLLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 11,
      sticking: "RLLLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 12,
    sticking: "LRRRLRRRLRRRLRRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 12,
      sticking: "LRRRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 12,
      sticking: "LRRRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 13,
    sticking: "RRRRLLLLRRRRLLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 13,
      sticking: "RRRRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 13,
      sticking: "RRRRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 14,
    sticking: "RLRLRRLLRLRLRRLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 14,
      sticking: "RLRLRRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 14,
      sticking: "RLRLRRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 15,
    sticking: "LRLRLLRRLRLRLLRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 15,
      sticking: "LRLRLLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 15,
      sticking: "LRLRLLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 16,
    sticking: "RLRLRLRRLRLRLRLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 16,
      sticking: "RLRLRLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 16,
      sticking: "LRLRLRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 17,
    sticking: "RLRLRLLRLRLRLRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 17,
      sticking: "RLRLRLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 17,
      sticking: "LRLRLRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 18,
    sticking: "RLRLRRLRLRLRLLRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 18,
      sticking: "RLRLRRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 18,
      sticking: "LRLRLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 19,
    sticking: "RLRLRRRLRLRLRRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 19,
      sticking: "RLRLRRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 19,
      sticking: "RLRLRRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 20,
    sticking: "LRLRLLLRLRLRLLLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 20,
      sticking: "LRLRLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 20,
      sticking: "LRLRLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 21,
    sticking: "RLRLRLLLRLRLRLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 21,
      sticking: "RLRLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 21,
      sticking: "RLRLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 22,
    sticking: "LRLRLRRRLRLRLRRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 22,
      sticking: "LRLRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 22,
      sticking: "LRLRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 23,
    sticking: "RLRLRRRRLRLRLLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 23,
      sticking: "RLRLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 23,
      sticking: "LRLRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 24,
    sticking: "RRLLRLRRLLRRLRLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 24,
      sticking: "RRLLRLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 24,
      sticking: "LLRRLRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 25,
    sticking: "RRLLRLLRLLRRLRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 25,
      sticking: "RRLLRLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 25,
      sticking: "LLRRLRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 26,
    sticking: "RRLLRRLRLLRRLLRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 26,
      sticking: "RRLLRRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 26,
      sticking: "LLRRLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 27,
    sticking: "RRLLLLRRRRLLLLRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 27,
      sticking: "RRLLLLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 27,
      sticking: "RRLLLLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 28,
    sticking: "RRLLRRRLRRLLRRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 28,
      sticking: "RRLLRRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 28,
      sticking: "RRLLRRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 29,
    sticking: "LLRRLLLRLLRRLLLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 29,
      sticking: "LLRRLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 29,
      sticking: "LLRRLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 30,
    sticking: "RRLLRLLLRRLLRLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 30,
      sticking: "RRLLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 30,
      sticking: "RRLLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 31,
    sticking: "LLRRLRRRLLRRLRRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 31,
      sticking: "LLRRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 31,
      sticking: "LLRRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 32,
    sticking: "RRLLRRRRLLRRLLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 32,
      sticking: "RRLLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 32,
      sticking: "LLRRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 33,
    sticking: "RLRRLRRLRLRRLRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 33,
      sticking: "RLRRLRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 33,
      sticking: "RLRRLRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 34,
    sticking: "LRLLRLLRLRLLRLLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 34,
      sticking: "LRLLRLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 34,
      sticking: "LRLLRLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 35,
    sticking: "RLRRLLRLRLRRLLRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 35,
      sticking: "RLRRLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 35,
      sticking: "RLRRLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 36,
    sticking: "LRLLRRLRLRLLRRLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 36,
      sticking: "LRLLRRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 36,
      sticking: "LRLLRRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 37,
    sticking: "RLRRRLRRRLRRRLRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 37,
      sticking: "RLRRRLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 37,
      sticking: "RLRRRLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 38,
    sticking: "LRLLLRLLLRLLLRLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 38,
      sticking: "LRLLLRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 38,
      sticking: "LRLLLRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 39,
    sticking: "RLRRLLLRLRLLRRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 39,
      sticking: "RLRRLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 39,
      sticking: "LRLLRRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 40,
    sticking: "RLRRLRRRLRLLRLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 40,
      sticking: "RLRRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 40,
      sticking: "LRLLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 41,
    sticking: "RLRRLLLLRLRRLLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 41,
      sticking: "RLRRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 41,
      sticking: "RLRRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 42,
    sticking: "LRLLRRRRLRLLRRRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 42,
      sticking: "LRLLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 42,
      sticking: "LRLLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 43,
    sticking: "RLLRLLRLRLLRLLRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 43,
      sticking: "RLLRLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 43,
      sticking: "RLLRLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 44,
    sticking: "LRRLRRLRLRRLRRLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 44,
      sticking: "LRRLRRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 44,
      sticking: "LRRLRRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 45,
    sticking: "RLLRRLLRRLLRRLLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 45,
      sticking: "RLLRRLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 45,
      sticking: "RLLRRLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 46,
    sticking: "LRRLLRRLLRRLLRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 46,
      sticking: "LRRLLRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 46,
      sticking: "LRRLLRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 47,
    sticking: "RLLRLLLRLRRLRRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 47,
      sticking: "RLLRLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 47,
      sticking: "LRRLRRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 48,
    sticking: "RLLRLRRRLRRLRLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 48,
      sticking: "RLLRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 48,
      sticking: "LRRLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 49,
    sticking: "RLLRLLLLRLLRLLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 49,
      sticking: "RLLRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 49,
      sticking: "RLLRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 50,
    sticking: "LRRLRRRRLRRLRRRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 50,
      sticking: "LRRLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 50,
      sticking: "LRRLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 51,
    sticking: "RRLRRRLRRRLRRRLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 51,
      sticking: "RRLRRRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 51,
      sticking: "RRLRRRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 52,
    sticking: "LLRLLLRLLLRLLLRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 52,
      sticking: "LLRLLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 52,
      sticking: "LLRLLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 53,
    sticking: "RRLRLLLRLLRLRRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 53,
      sticking: "RRLRLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 53,
      sticking: "LLRLRRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 54,
    sticking: "RRLRLRRRLLRLRLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 54,
      sticking: "RRLRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 54,
      sticking: "LLRLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 55,
    sticking: "RRLRLLLLRRLRLLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 55,
      sticking: "RRLRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 55,
      sticking: "RRLRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 56,
    sticking: "LLRLRRRRLLRLRRRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 56,
      sticking: "LLRLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 56,
      sticking: "LLRLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 57,
    sticking: "RRRLLLLRRRRLLLLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 57,
      sticking: "RRRLLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 57,
      sticking: "RRRLLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 58,
    sticking: "RRRLRLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 58,
      sticking: "RRRLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 58,
      sticking: "RRRLRLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 59,
    sticking: "LLLRLRRRLLLRLRRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 59,
      sticking: "LLLRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 59,
      sticking: "LLLRLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 60,
    sticking: "RRRLRRRRLLLRLLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 60,
      sticking: "RRRLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 60,
      sticking: "LLLRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 61,
    sticking: "RLLLLRRRRLLLLRRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 61,
      sticking: "RLLLLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 61,
      sticking: "RLLLLRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 62,
    sticking: "RLLLRRRRLRRRLLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 62,
      sticking: "RLLLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 62,
      sticking: "LRRRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 63,
    sticking: "RRRLLLRRRLLLRRRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 63,
      sticking: "RRRLLLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 63,
      sticking: "RLLLRRRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 64,
    sticking: "LLLRRRLLLRRRLLLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 64,
      sticking: "LLLRRRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 64,
      sticking: "LRRRLLLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 65,
    sticking: "RRLRRLRRLRRLRLRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 65,
      sticking: "RRLRRLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 65,
      sticking: "LRRLRLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 66,
    sticking: "LLRLLRLLRLLRLRLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 66,
      sticking: "LLRLLRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 66,
      sticking: "RLLRLRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 67,
    sticking: "RLLRLLRLLRLLRLRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 67,
      sticking: "RLLRLLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 67,
      sticking: "LRLLRLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 68,
    sticking: "LRRLRRLRRLRRLRLR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 68,
      sticking: "LRRLRRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 68,
      sticking: "RLRRLRLR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 69,
    sticking: "RLRRLLLLRRRRLRLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 69,
      sticking: "RLRRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 69,
      sticking: "RRRRLRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 70,
    sticking: "RRLLRLRRLLLLRRRR",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 70,
      sticking: "RRLLRLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 70,
      sticking: "LLLLRRRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 71,
    sticking: "LLRRLRLLRRRRLLLL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 71,
      sticking: "LLRRLRLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 71,
      sticking: "RRRRLLLL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
  {
    section: "Single Beat Combinations",
    exercise: 72,
    sticking: "RRRRLLRRLRRLRLRL",
    count: "1+2+3+4+|1+2+3+4+",
    class: "sc-sbc",
    measure1: {
      exercise: 72,
      sticking: "RRRRLLRR",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "R",
      timeSignature: "4/4",
      inverted: false,
    },
    measure2: {
      exercise: 72,
      sticking: "LRRLRLRL",
      grid: "1/8 notes",
      count: "1+2+3+4+",
      lead: "L",
      timeSignature: "4/4",
      inverted: false,
    },
    inverted: false,
  },
];

module.exports = singleBeatCombinations;
